name: ZJU-nCov-Hitcarder Sample

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - username: ZJU_USERNAME
            password: ZJU_PASSWORD
            pushplus_token: PUSHPLUS_TOKEN
          - username: ZJU_USERNAME2
            password: ZJU_PASSWORD2
            pushplus_token: PUSHPLUS_TOKEN2
          - username: ZJU_USERNAME3
            password: ZJU_PASSWORD3
            pushplus_token: PUSHPLUS_TOKEN3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Working
        uses: Long0x0/zju-ncov-hitcarder@master
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          pushplus_token: ${{ secrets[matrix.pushplus_token] }}
